version: '3.7'

services:
  test-php:
    build:
      context: ./
      dockerfile: deploy/php/Dockerfile
    image: php8
    container_name: php8test
    env_file:
      - ./.env
    volumes:
      - ./code:/var/www/html
      - ./deploy/php/local.php.ini:/usr/local/etc/php/php.ini
    networks:
      test-net:
        ipv4_address: 192.168.2.2

  test-mysql:
    image: mysql:5.6
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    networks:
      test-net:
        ipv4_address: 192.168.2.3
networks:
  test-net:
    external: true